controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.155
    wheel_radius: 0.0325

    # use_stamped_vel: true

    # open_loop: false

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: odom
    # pose_covariance_diagnol: x
    # twist_covariance_diagnol: x
    # enable_odom_tf: true

    # cmd_vel_timeout: 1.0
    # publish_limited_velocity: true
    # velocity_rolling_window_size: 10

    # linear.x.has_velocity_limits: true
    # linear.x.has_acceleration_limits: true
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: 1.5
    # linear.x.min_velocity: -1.5
    # linear.x.max_acceleration: 4.0
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    # angular.z.has_jerk_limits: false
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 8.0
    angular.z.min_acceleration: -8.0
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
# joint_broad:
#   ros__parametes:
